### ISSUE TITLE
MacBook Air, M1, 2020, 8GB ram

### ISSUE THREAD

**Issue by edbond** [philipturner/applegpuinfo#11]
MacBook Air, M1, 2020, 8GB ram

GPU name: Apple M1
GPU vendor: Apple
GPU core count: 8
GPU clock frequency: 1.278 GHz
GPU bandwidth: 68.3 GB/s
GPU FLOPS: 2.617 TFLOPS
GPU IPS: 1.309 TIPS
GPU system level cache: 8 MB
GPU memory: 8 GB
GPU family: Apple 7

**Comment by philipturner** [comment]
Added (https://github.com/philipturner/applegpuinfo/commit/24226431095c614c88de686ea5afcc99d7cb31f5)
