### ISSUE TITLE
Apple M1 Max 2021

### ISSUE THREAD

**Issue by theschles** [philipturner/applegpuinfo#2]
Model Identifier:	MacBookPro18,4
  Model Number:	G15HBLL/A
Total Number of Cores:	10 (8 performance and 2 efficiency)

GPU name: Apple M1 Max
GPU core count: 32
GPU clock frequency: 1.296 GHz
GPU bandwidth: 409.6 GB/s
GPU FLOPS: 10.617 TFLOPS
GPU IPS: 5.308 TIPS
GPU system level cache: 48 MB
GPU memory: 32 GB
GPU family: Apple 7

**Comment by philipturner** [comment]
Alright. Thanks for the info. I already have that config in my table, but it's nice to know it runs on someone else's M1 Max.
