### ISSUE TITLE
Apple MBP 2017 Retina

### ISSUE THREAD

**Issue by theschles** [philipturner/applegpuinfo#3]
➜ system_profiler SPSoftwareDataType SPHardwareDataType
...
 Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro14,3
      Processor Name: Quad-Core Intel Core i7
      Processor Speed: 2.8 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB

➜ swift run gpuinfo list
Fetching https://github.com/apple/swift-argument-parser
Fetched https://github.com/apple/swift-argument-parser (6.12s)
Fetching https://github.com/devicekit/DeviceKit
Fetched https://github.com/devicekit/DeviceKit (4.48s)
Creating working copy for https://github.com/apple/swift-argument-parser
Working copy of https://github.com/apple/swift-argument-parser resolved at main
Creating working copy for https://github.com/devicekit/DeviceKit
Working copy of https://github.com/devicekit/DeviceKit resolved at master
Building for debugging...
[50/50] Linking gpuinfo
Build complete! (15.97s)
Error: The operation couldn’t be completed. (AppleGPUInfo.GPUInfoError error 1.)

**Comment by philipturner** [comment]
I’m going to try getting Intel GPUs supported in this library, but AMD GPUs might have to wait a little while longer. In the meantime, try testing whether the AppleGPUInfo device initializer can make it all the way to the `fatalError`.

**Comment by theschles** [comment]
Yep it got to the fatal error:

```
➜ git pull
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 22 (delta 7), reused 14 (delta 5), pack-reused 0
Unpacking objects: 100% (22/22), 6.08 KiB | 151.00 KiB/s, done.
From https://github.com/philipturner/applegpuinfo
   5f63ffe..928b493  main       -> origin/main
Updating 5f63ffe..928b493
Fast-forward
 README.md                                                |   4 +-
 Sources/AppleGPUInfo/AppleGPUInfo.swift                  | 138 ++++++++++++++++++++++++++++++++++++++++++++---------------
 Sources/AppleGPUInfo/CAppleGPUInfo.swift                 |  41 +++++++-----------
 Sources/AppleGPUInfo/include/AppleGPUInfo/AppleGPUInfo.h |  80 ++++++++++++++++++++++++++++++++++
 Sources/AppleGPUInfoTool/main.swift                      |   1 +
 Tests/AppleGPUInfoTests/AppleGPUInfoTests.swift          |  71 ++++++++++++++++++++++++++++++
 6 files changed, 275 insertions(+), 60 deletions(-)
 create mode 100644 Sources/AppleGPUInfo/include/AppleGPUInfo/AppleGPUInfo.h

phil in applegpuinfo at PhilipsMBP2017 on  main
➜ swift run gpuinfo list
Building for debugging...
/Users/phil/Documents/GitHub/applegpuinfo/Sources/AppleGPUInfo/AppleGPUInfo.swift:246:9: warning: will never be executed
    var tier: Tier
        ^
/Users/phil/Documents/GitHub/applegpuinfo/Sources/AppleGPUInfo/AppleGPUInfo.swift:202:5: note: a call to a never-returning function
    fatalError("Intel Macs are not supported yet.")
    ^
/Users/phil/Documents/GitHub/applegpuinfo/Sources/AppleGPUInfo/AppleGPUInfo.swift:246:9: warning: will never be executed
    var tier: Tier
        ^
/Users/phil/Documents/GitHub/applegpuinfo/Sources/AppleGPUInfo/AppleGPUInfo.swift:202:5: note: a call to a never-returning function
    fatalError("Intel Macs are not supported yet.")
    ^
[6/6] Linking gpuinfo
Build complete! (4.63s)
AppleGPUInfo/AppleGPUInfo.swift:202: Fatal error: Intel Macs are not supported yet.
[1]    31148 illegal hardware instruction  swift run gpuinfo list
```

**Comment by philipturner** [comment]
I'm not sure whether I will have time to port to AMD GPUs before launching my library. Optimization requires a lot of back-and-forth debugging with low-latency access to hardware. However, I do own an Intel Mac mini. I'm interested in how AppleGPUInfo responds to the Intel GPU in your MacBook.

**Comment by philipturner** [comment]
I'm also not ruling out AMD GPUs _indefinitely_, just maximizing the chance I can release the library by the end of this summer. I might have to cut things like Winograd convolutions too.

**Comment by theschles** [comment]
Apologies, I've been on vacation.

```
commit c0c91273ed74c143dfc815db570dd113b1e2c0d1 (HEAD -> main, origin/main, origin/HEAD)
Author: Philip Turner <philipturner.AR@gmail.com>
Date:   Tue Jun 13 08:28:53 2023 -0400

    More clarifications
```


```
AMD Radeon Pro 560 - 4294969339
Intel(R) HD Graphics 630 - 4294968607
```

```
➜ export GPUINFO_REGISTRY_ID=4294968607
➜ swift run gpuinfo list
Building for debugging...
Build complete! (0.63s)
AppleGPUInfo/AppleGPUInfo.swift:214: Fatal error: Intel Macs are not supported yet.
[1]    32346 illegal hardware instruction  swift run gpuinfo list
```


```
➜ export GPUINFO_REGISTRY_ID=4294969339
➜ swift run gpuinfo list
Building for debugging...
Build complete! (0.75s)
AppleGPUInfo/AppleGPUInfo.swift:214: Fatal error: Intel Macs are not supported yet.
[1]    32955 illegal hardware instruction  swift run gpuinfo list
```
