### ISSUE TITLE
A14 (iPhone 12 pro)

### ISSUE THREAD

**Issue by bodza** [philipturner/applegpuinfo#9]
GPU name: Apple A14 GPU
GPU vendor: Apple
GPU core count: 4
GPU clock frequency: 1.278 GHz
GPU bandwidth: 34.1 GB/s
GPU FLOPS: 0.654 TFLOPS
GPU IPS: 0.654 TIPS
GPU system level cache: 16 MB
GPU memory: 5.54 GB
GPU family: Apple 7

**Comment by philipturner** [comment]
Added to the table
